# docker-compose skema versi 3.7
version: "3.7"
# service-service yang diperlukan
services:
  # service pertama, item-app / web app
  item-app:
    # docker image yang dipakai
    image: ghcr.io/triwjy/item-app:v1
    # mapping port container (8080) ke host (80)
    ports:
      - 80:8080
    # menunggu service (container) item-db deploy terlebih dahulu
    depends_on: 
      - item-db
    # selalu restart kontainer ketika terhenti
    restart: always

  # service kedua, item-db / database
  item-db:
    # docker image yang dipakai
    image: mongo:3
    # menggunakan volume app-db dan dipasang pada /data/db di kontainer
    volumes:
      - app-db:/data/db
    # selalu restart kontainer ketika terhenti
    restart: always
# menggunakan (membuat volume baru jika belum ada) volume app-db
volumes:
  app-db: