version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.2
workflows:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: 'DL4005,DL4005,DL3008'
  test-app:
    jobs:
      - build-and-test
  build-app-karsajobs:
    jobs:
      - docker/publish:
          image: triwjy/karsajobs
          registry: ghcr.io
jobs:
  build-and-test:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Test
          command: go test -v -short --count=1 $(go list ./...)